"""
Comprehensive Government Schemes Database
Covers all categories: Students, Farmers, Women, Elderly, Disabled, SC/ST/OBC, Entrepreneurs, etc.
"""

COMPREHENSIVE_SCHEMES = [
    # ==================== STUDENT SCHEMES ====================
    {
        "name": "National Scholarship for Higher Education",
        "short_description": "Central government scholarship for meritorious students pursuing higher education",
        "full_description": "This scholarship provides financial assistance to students from economically weaker sections who have secured admission in recognized higher education institutions. The scholarship covers tuition fees and provides maintenance allowance.",
        "category": "student",
        "state": "Central",
        "min_age": 18,
        "max_age": 35,
        "max_income": 800000,
        "occupation": "student",
        "gender": "Any",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://scholarships.gov.in/",
        "application_process": "1. Register on National Scholarship Portal\n2. Fill application form with academic details\n3. Upload required documents (income certificate, mark sheets)\n4. Submit application before deadline\n5. Track application status online"
    },
    {
        "name": "Post Matric Scholarship for SC Students",
        "short_description": "Financial assistance for SC students pursuing post-matriculation studies",
        "full_description": "Central sector scheme providing financial support to SC students for post-matric education including graduation, post-graduation, and professional courses.",
        "category": "student",
        "state": "Central",
        "min_age": 16,
        "max_age": 35,
        "max_income": 250000,
        "occupation": "student",
        "gender": "Any",
        "caste": "SC",
        "disability": "Any",
        "official_link": "https://scholarships.gov.in/",
        "application_process": "1. Register on NSP with Aadhaar\n2. Fill scholarship form\n3. Upload caste certificate, income certificate, mark sheets\n4. Submit to institution for verification\n5. Track disbursement status"
    },
    {
        "name": "Post Matric Scholarship for ST Students",
        "short_description": "Financial assistance for ST students pursuing post-matriculation studies",
        "full_description": "Central sector scheme providing financial support to ST students for post-matric education including graduation, post-graduation, and professional courses.",
        "category": "student",
        "state": "Central",
        "min_age": 16,
        "max_age": 35,
        "max_income": 250000,
        "occupation": "student",
        "gender": "Any",
        "caste": "ST",
        "disability": "Any",
        "official_link": "https://scholarships.gov.in/",
        "application_process": "1. Register on NSP with Aadhaar\n2. Fill scholarship form\n3. Upload ST certificate, income certificate, mark sheets\n4. Submit to institution for verification\n5. Track disbursement status"
    },
    {
        "name": "Post Matric Scholarship for OBC Students",
        "short_description": "Financial assistance for OBC students pursuing post-matriculation studies",
        "full_description": "Central sector scheme providing financial support to OBC students for post-matric education. Covers tuition fees and maintenance allowance.",
        "category": "student",
        "state": "Central",
        "min_age": 16,
        "max_age": 35,
        "max_income": 100000,
        "occupation": "student",
        "gender": "Any",
        "caste": "OBC",
        "disability": "Any",
        "official_link": "https://scholarships.gov.in/",
        "application_process": "1. Register on NSP portal\n2. Fill application with academic details\n3. Upload OBC certificate (non-creamy layer), income certificate\n4. Submit for institutional verification\n5. Receive scholarship in bank account"
    },
    {
        "name": "Karnataka Vidyasiri Scholarship",
        "short_description": "Merit-cum-means scholarship for students in professional courses",
        "full_description": "Scholarship for students pursuing professional courses like Engineering, Medical, and Management in Karnataka. Provides financial assistance based on merit and family income.",
        "category": "student",
        "state": "Karnataka",
        "min_age": 17,
        "max_age": 28,
        "max_income": 500000,
        "occupation": "student",
        "gender": "Any",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://www.myscheme.gov.in/schemes/vidyasiri",
        "application_process": "1. Register on Vidyasiri portal\n2. Fill application with course and institution details\n3. Upload income certificate and admission proof\n4. Submit previous year mark sheets\n5. Institution verification\n6. Scholarship disbursed to institution account"
    },
    {
        "name": "Pre-Matric Scholarship for SC/ST Students",
        "short_description": "Scholarship for SC/ST students in classes 9 and 10",
        "full_description": "Central scheme to support SC/ST students in classes 9 and 10 to reduce dropout rates and encourage education.",
        "category": "student",
        "state": "Central",
        "min_age": 13,
        "max_age": 18,
        "max_income": 250000,
        "occupation": "student",
        "gender": "Any",
        "caste": "SC/ST",
        "disability": "Any",
        "official_link": "https://scholarships.gov.in/",
        "application_process": "1. Apply through school\n2. Submit caste certificate and income proof\n3. School verifies and forwards application\n4. Scholarship credited to student's account"
    },
    
    # ==================== FARMER SCHEMES ====================
    {
        "name": "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)",
        "short_description": "Direct income support of ₹6000/year to all landholding farmers",
        "full_description": "Central government scheme providing ₹6000 per year in three equal installments to all landholding farmer families. The amount is directly transferred to bank accounts.",
        "category": "farmer",
        "state": "Central",
        "min_age": 18,
        "max_age": None,
        "max_income": None,
        "occupation": "farmer",
        "gender": "Any",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://pmkisan.gov.in/",
        "application_process": "1. Visit PM-KISAN portal or nearest CSC\n2. Register with Aadhaar number\n3. Provide land ownership details\n4. Link bank account\n5. Submit application\n6. Receive installments directly in bank account"
    },
    {
        "name": "Karnataka Farmer Welfare Scheme - Equipment Subsidy",
        "short_description": "Subsidy for farmers to purchase modern agricultural equipment",
        "full_description": "This scheme provides financial assistance to farmers in Karnataka for purchasing modern agricultural equipment like tractors, tillers, and irrigation systems. The subsidy covers up to 50% of equipment cost.",
        "category": "farmer",
        "state": "Karnataka",
        "min_age": 18,
        "max_age": 65,
        "max_income": 500000,
        "occupation": "farmer",
        "gender": "Any",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://raitamitra.karnataka.gov.in/",
        "application_process": "1. Visit nearest Raitha Samparka Kendra or apply online\n2. Submit land ownership documents\n3. Provide income certificate and Aadhaar\n4. Select equipment from approved vendor list\n5. Get quotation and submit for approval\n6. Receive subsidy after equipment purchase verification"
    },
    {
        "name": "PM Fasal Bima Yojana (Crop Insurance)",
        "short_description": "Comprehensive crop insurance for farmers against natural calamities",
        "full_description": "Provides insurance coverage and financial support to farmers in case of crop failure due to natural calamities, pests, and diseases.",
        "category": "farmer",
        "state": "Central",
        "min_age": 18,
        "max_age": None,
        "max_income": None,
        "occupation": "farmer",
        "gender": "Any",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://pmfby.gov.in/",
        "application_process": "1. Apply through bank or CSC within crop season\n2. Provide land records and Aadhaar\n3. Pay nominal premium\n4. Get insurance coverage\n5. Claim settlement in case of crop loss"
    },
    {
        "name": "Kisan Credit Card (KCC)",
        "short_description": "Credit facility for farmers to meet agricultural expenses",
        "full_description": "Provides adequate and timely credit support to farmers for cultivation and other needs. Offers flexible repayment terms and low interest rates.",
        "category": "farmer",
        "state": "Central",
        "min_age": 18,
        "max_age": 75,
        "max_income": None,
        "occupation": "farmer",
        "gender": "Any",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://www.india.gov.in/spotlight/kisan-credit-card-kcc",
        "application_process": "1. Visit nearest bank branch\n2. Submit land documents and Aadhaar\n3. Fill KCC application form\n4. Bank verification\n5. Receive KCC with credit limit"
    },
    
    # ==================== WOMEN SCHEMES ====================
    {
        "name": "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
        "short_description": "Maternity benefit of ₹5000 for pregnant and lactating mothers",
        "full_description": "Cash incentive provided to pregnant women and lactating mothers for the first living child to meet increased nutritional needs and compensate for wage loss.",
        "category": "women",
        "state": "Central",
        "min_age": 18,
        "max_age": 45,
        "max_income": None,
        "occupation": "Any",
        "gender": "Female",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://pmmvy.wcd.gov.in/",
        "application_process": "1. Register at Anganwadi Centre or health facility\n2. Submit pregnancy registration documents\n3. Receive payment in three installments\n4. Complete health checkups as per schedule"
    },
    {
        "name": "Beti Bachao Beti Padhao",
        "short_description": "Scheme to prevent gender-biased sex selection and promote girl child education",
        "full_description": "Multi-sectoral initiative addressing declining Child Sex Ratio and promoting education and empowerment of girls.",
        "category": "women",
        "state": "Central",
        "min_age": 0,
        "max_age": 21,
        "max_income": None,
        "occupation": "Any",
        "gender": "Female",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://wcd.nic.in/bbbp-schemes",
        "application_process": "1. Open Sukanya Samriddhi Account in post office or bank\n2. Deposit minimum ₹250 annually\n3. Get tax benefits and high interest\n4. Maturity after girl turns 21"
    },
    {
        "name": "Mahila Shakti Kendra",
        "short_description": "Empowerment program for rural women through community participation",
        "full_description": "Provides opportunities for skill development, employment, digital literacy, health and nutrition for rural women.",
        "category": "women",
        "state": "Central",
        "min_age": 18,
        "max_age": 60,
        "max_income": None,
        "occupation": "Any",
        "gender": "Female",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://wcd.nic.in/",
        "application_process": "1. Contact district Mahila Shakti Kendra\n2. Enroll in skill development programs\n3. Participate in community activities\n4. Access employment opportunities"
    },
    {
        "name": "Karnataka Bhagyalakshmi Scheme",
        "short_description": "Financial assistance for girl child education and marriage",
        "full_description": "Karnataka government scheme providing financial assistance to BPL families for girl child's education and marriage expenses.",
        "category": "women",
        "state": "Karnataka",
        "min_age": 0,
        "max_age": 25,
        "max_income": 100000,
        "occupation": "Any",
        "gender": "Female",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://www.myscheme.gov.in/schemes/bls",
        "application_process": "1. Apply within one year of girl child's birth\n2. Submit BPL card and birth certificate\n3. Open savings account in girl's name\n4. Receive installments at education milestones"
    },
    {
        "name": "Stand Up India Scheme for Women Entrepreneurs",
        "short_description": "Bank loans for women entrepreneurs to start greenfield enterprises",
        "full_description": "Facilitates bank loans between ₹10 lakh to ₹1 crore for women entrepreneurs in manufacturing, services, or trading sector.",
        "category": "entrepreneur",
        "state": "Central",
        "min_age": 18,
        "max_age": 65,
        "max_income": None,
        "occupation": "entrepreneur",
        "gender": "Female",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://www.standupmitra.in/",
        "application_process": "1. Prepare business plan\n2. Apply through bank or online portal\n3. Submit project report and documents\n4. Bank appraisal and sanction\n5. Receive loan for business setup"
    },
    
    # ==================== ELDERLY SCHEMES ====================
    {
        "name": "Indira Gandhi National Old Age Pension Scheme",
        "short_description": "Monthly pension of ₹200-500 for elderly citizens below poverty line",
        "full_description": "Central assistance to state governments for providing pension to elderly persons aged 60 years and above who are destitute.",
        "category": "elderly",
        "state": "Central",
        "min_age": 60,
        "max_age": None,
        "max_income": None,
        "occupation": "Any",
        "gender": "Any",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://nsap.nic.in/",
        "application_process": "1. Apply at local panchayat or municipal office\n2. Submit age proof and BPL card\n3. Verification by authorities\n4. Pension credited monthly to bank account"
    },
    {
        "name": "Pradhan Mantri Vaya Vandana Yojana",
        "short_description": "Pension scheme for senior citizens with assured returns",
        "full_description": "Provides assured pension based on guaranteed rate of return of 7.4% per annum for 10 years. Available for senior citizens aged 60 years and above.",
        "category": "elderly",
        "state": "Central",
        "min_age": 60,
        "max_age": None,
        "max_income": None,
        "occupation": "Any",
        "gender": "Any",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://licindia.in/",
        "application_process": "1. Visit LIC branch or apply online\n2. Choose pension mode (monthly/quarterly/yearly)\n3. Pay premium (minimum ₹1.5 lakh)\n4. Receive regular pension payments"
    },
    {
        "name": "Karnataka Sandhya Suraksha Scheme",
        "short_description": "Pension scheme for destitute elderly in Karnataka",
        "full_description": "State government pension for elderly persons above 65 years who are destitute and have no means of subsistence.",
        "category": "elderly",
        "state": "Karnataka",
        "min_age": 65,
        "max_age": None,
        "max_income": 50000,
        "occupation": "Any",
        "gender": "Any",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://ahinda.karnataka.gov.in/",
        "application_process": "1. Apply at taluk social welfare office\n2. Submit age proof and income certificate\n3. Verification by officials\n4. Monthly pension to bank account"
    },
    
    # ==================== DISABILITY SCHEMES ====================
    {
        "name": "Indira Gandhi National Disability Pension Scheme",
        "short_description": "Monthly pension for persons with severe or multiple disabilities",
        "full_description": "Provides pension to persons with severe or multiple disabilities aged 18-59 years who are below poverty line.",
        "category": "disability",
        "state": "Central",
        "min_age": 18,
        "max_age": 59,
        "max_income": None,
        "occupation": "Any",
        "gender": "Any",
        "caste": "Any",
        "disability": "Yes",
        "official_link": "https://nsap.nic.in/",
        "application_process": "1. Apply at local panchayat/municipal office\n2. Submit disability certificate (80% or more)\n3. Provide BPL card and Aadhaar\n4. Verification and approval\n5. Monthly pension to bank account"
    },
    {
        "name": "Deendayal Disabled Rehabilitation Scheme",
        "short_description": "Support for rehabilitation of persons with disabilities",
        "full_description": "Provides financial assistance to NGOs for running rehabilitation centers, special schools, and vocational training for persons with disabilities.",
        "category": "disability",
        "state": "Central",
        "min_age": 0,
        "max_age": None,
        "max_income": None,
        "occupation": "Any",
        "gender": "Any",
        "caste": "Any",
        "disability": "Yes",
        "official_link": "https://disabilityaffairs.gov.in/",
        "application_process": "1. Contact registered NGO or rehabilitation center\n2. Submit disability certificate\n3. Enroll in rehabilitation/training program\n4. Receive free services and support"
    },
    {
        "name": "Assistance to Disabled Persons for Purchase of Aids and Appliances (ADIP)",
        "short_description": "Financial assistance for purchasing aids and appliances for disabled persons",
        "full_description": "Provides assistive devices like wheelchairs, hearing aids, artificial limbs, etc. to persons with disabilities from economically weaker sections.",
        "category": "disability",
        "state": "Central",
        "min_age": 0,
        "max_age": None,
        "max_income": 15000,
        "occupation": "Any",
        "gender": "Any",
        "caste": "Any",
        "disability": "Yes",
        "official_link": "https://disabilityaffairs.gov.in/",
        "application_process": "1. Apply through district social welfare office\n2. Submit disability certificate and income proof\n3. Medical assessment by authorized center\n4. Receive aids/appliances free of cost"
    },
    {
        "name": "Karnataka Disabled Persons Pension Scheme",
        "short_description": "Monthly pension for disabled persons in Karnataka",
        "full_description": "State government pension for persons with 40% or more disability who are economically weak.",
        "category": "disability",
        "state": "Karnataka",
        "min_age": 18,
        "max_age": None,
        "max_income": 50000,
        "occupation": "Any",
        "gender": "Any",
        "caste": "Any",
        "disability": "Yes",
        "official_link": "https://ahinda.karnataka.gov.in/",
        "application_process": "1. Apply at taluk social welfare office\n2. Submit disability certificate (40% or more)\n3. Provide income certificate and Aadhaar\n4. Verification and approval\n5. Monthly pension credited to account"
    },
    
    # ==================== ENTREPRENEUR SCHEMES ====================
    {
        "name": "Pradhan Mantri Mudra Yojana (PMMY)",
        "short_description": "Loans up to ₹10 lakh for micro and small enterprises",
        "full_description": "Provides funding to non-corporate, non-farm small/micro enterprises through three categories: Shishu (up to ₹50,000), Kishore (₹50,001 to ₹5 lakh), Tarun (₹5 lakh to ₹10 lakh).",
        "category": "entrepreneur",
        "state": "Central",
        "min_age": 18,
        "max_age": None,
        "max_income": None,
        "occupation": "entrepreneur",
        "gender": "Any",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://www.mudra.org.in/",
        "application_process": "1. Prepare business plan\n2. Visit nearest bank or NBFC\n3. Fill Mudra loan application\n4. Submit business documents\n5. Loan approval and disbursement"
    },
    {
        "name": "Stand Up India Scheme",
        "short_description": "Bank loans for SC/ST and women entrepreneurs",
        "full_description": "Facilitates bank loans between ₹10 lakh to ₹1 crore to at least one SC/ST and one woman entrepreneur per bank branch for greenfield enterprises.",
        "category": "entrepreneur",
        "state": "Central",
        "min_age": 18,
        "max_age": 65,
        "max_income": None,
        "occupation": "entrepreneur",
        "gender": "Any",
        "caste": "SC/ST",
        "disability": "Any",
        "official_link": "https://www.standupmitra.in/",
        "application_process": "1. Prepare detailed project report\n2. Apply through bank or online\n3. Submit caste certificate and business plan\n4. Bank appraisal\n5. Loan sanction and disbursement"
    },
    {
        "name": "Startup India Seed Fund Scheme",
        "short_description": "Financial assistance to startups for proof of concept and prototype development",
        "full_description": "Provides seed funding up to ₹20 lakh for validation of proof of concept or prototype development and up to ₹50 lakh for market entry and commercialization.",
        "category": "entrepreneur",
        "state": "Central",
        "min_age": 18,
        "max_age": None,
        "max_income": None,
        "occupation": "entrepreneur",
        "gender": "Any",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://www.startupindia.gov.in/",
        "application_process": "1. Register on Startup India portal\n2. Get DPIIT recognition\n3. Apply through incubator\n4. Submit business plan and pitch\n5. Evaluation and fund disbursement"
    },
    {
        "name": "Karnataka Startup Policy - Seed Fund",
        "short_description": "Seed funding for startups in Karnataka",
        "full_description": "Karnataka government provides seed funding up to ₹50 lakh to eligible startups for product development and market entry.",
        "category": "entrepreneur",
        "state": "Karnataka",
        "min_age": 18,
        "max_age": None,
        "max_income": None,
        "occupation": "entrepreneur",
        "gender": "Any",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://startup.karnataka.gov.in/",
        "application_process": "1. Register on Karnataka Startup portal\n2. Submit detailed business plan\n3. Pitch to evaluation committee\n4. Due diligence and approval\n5. Seed fund disbursement"
    },
    
    # ==================== GENERAL WELFARE SCHEMES ====================
    {
        "name": "Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (PM-JAY)",
        "short_description": "Health insurance cover of ₹5 lakh per family per year",
        "full_description": "World's largest health insurance scheme providing free access to health care services for poor and vulnerable families.",
        "category": "health",
        "state": "Central",
        "min_age": 0,
        "max_age": None,
        "max_income": None,
        "occupation": "Any",
        "gender": "Any",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://pmjay.gov.in/",
        "application_process": "1. Check eligibility on PM-JAY website\n2. Visit nearest Ayushman Mitra or hospital\n3. Provide Aadhaar and family details\n4. Get Ayushman card\n5. Avail cashless treatment at empaneled hospitals"
    },
    {
        "name": "Pradhan Mantri Awas Yojana (PMAY) - Urban",
        "short_description": "Housing for all in urban areas with subsidy on home loans",
        "full_description": "Provides interest subsidy on home loans and direct assistance for construction of houses to economically weaker sections and low-income groups.",
        "category": "housing",
        "state": "Central",
        "min_age": 18,
        "max_age": None,
        "max_income": 1800000,
        "occupation": "Any",
        "gender": "Any",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://pmaymis.gov.in/",
        "application_process": "1. Apply online on PMAY portal\n2. Fill application with income and property details\n3. Submit Aadhaar and income certificate\n4. Verification by authorities\n5. Subsidy credited on loan approval"
    },
    {
        "name": "Pradhan Mantri Ujjwala Yojana",
        "short_description": "Free LPG connection to women from BPL households",
        "full_description": "Provides deposit-free LPG connection to women from BPL households to ensure universal coverage of cooking gas.",
        "category": "welfare",
        "state": "Central",
        "min_age": 18,
        "max_age": None,
        "max_income": None,
        "occupation": "Any",
        "gender": "Female",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://www.pmujjwalayojana.com/",
        "application_process": "1. Apply at nearest LPG distributor\n2. Submit BPL card and Aadhaar\n3. Provide address proof\n4. Verification by distributor\n5. Free LPG connection installation"
    },
    {
        "name": "National Rural Employment Guarantee Act (NREGA/MGNREGA)",
        "short_description": "100 days of guaranteed wage employment in rural areas",
        "full_description": "Provides at least 100 days of guaranteed wage employment in a financial year to every rural household whose adult members volunteer to do unskilled manual work.",
        "category": "employment",
        "state": "Central",
        "min_age": 18,
        "max_age": None,
        "max_income": None,
        "occupation": "Any",
        "gender": "Any",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://nrega.nic.in/",
        "application_process": "1. Apply at gram panchayat with photo and address proof\n2. Get job card within 15 days\n3. Apply for work when needed\n4. Work must be provided within 15 days\n5. Wages paid weekly or fortnightly"
    },
    {
        "name": "Pradhan Mantri Kaushal Vikas Yojana (PMKVY)",
        "short_description": "Skill development training for youth with monetary rewards",
        "full_description": "Flagship scheme for skill training of youth. Provides free training in various sectors with certification and monetary rewards on successful completion.",
        "category": "skill_development",
        "state": "Central",
        "min_age": 15,
        "max_age": 45,
        "max_income": None,
        "occupation": "Any",
        "gender": "Any",
        "caste": "Any",
        "disability": "Any",
        "official_link": "https://www.pmkvyofficial.org/",
        "application_process": "1. Register on PMKVY portal\n2. Choose training center and course\n3. Enroll in training program\n4. Complete training and assessment\n5. Receive certificate and monetary reward"
    },
]
